DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Stock;

CREATE TABLE Users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DOC VARCHAR(100) NOT NULL,
    TYPE_DOC VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(50),
    BIRTHDATE DATE,
    STATUS VARCHAR(50),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Address (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    STREET VARCHAR(100) NOT NULL,
    COMPLEMENT VARCHAR(100),
    NUMBER INT NOT NULL,
    ZIPCODE VARCHAR(50) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE Category (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE Book (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    ISBN VARCHAR(20) NOT NULL,
    PUBLICATION_YEAR INT,
    VOLUME INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE
);


CREATE TABLE Stock (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QTDTOTAL INT,
    QTDAVAILABLE INT,
    BOOK_ID INT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);